module.exports = {
  content: [
    "./pages/index.tsx",
    "./pages/_app.tsx",
    "./pages/404.js",
    "./pages/components/Header.tsx",
    "./pages/components/Hero.tsx",
    "./pages/components/Buttons.tsx",
    "./pages/components/Expect.tsx",
    "./pages/components/HQ.tsx",
    "./pages/components/Versatile.tsx",
    "./pages/components/Worked.tsx",
    "./pages/components/Clients.tsx",
    "./pages/components/Contact.tsx",
    "./pages/components/Footer.tsx",
    "./pages/components/Form.tsx",
    "./pages/letsgetstarted.tsx",
    "./pages/applicationdevelopment.tsx",
    "./pages/components/AppHero.tsx",
    "./pages/components/ServiceButtons.tsx",
    "./pages/components/HowApp.tsx",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
