import type { NextPage } from "next";
import Head from "next/head";
import Header from "./components/Header";
import Hero from "./components/Hero";
import Buttons from "./components/Buttons";
import Expect from "./components/Expect";
import HQ from "./components/HQ";
import Versatile from "./components/Versatile";
import Worked from "./components/Worked";
import Clients from "./components/Clients";
import Contact from "./components/Contact";
import Footer from "./components/Footer";
import { SSRProvider } from "react-bootstrap";

const Home: NextPage = () => {
  return (
    <div className="w-full overflow-hidden">
      <SSRProvider>
        <Head>
          <title>Greak Tech 2022</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header />

        <Hero />

        <div className="relative bottom-6">
          <Buttons />
        </div>

        <Expect />

        <HQ />

        <Versatile />

        <Worked />

        <Clients />

        <Contact />

        <Footer />
      </SSRProvider>
    </div>
  );
};

export default Home;
